trigger:
  branches:
    include:
      - main

pool:
  name: ec2-user

steps:
- script: |
    cd  FastAPI-Model_Serving 
    python3.11 -m venv myenv
    source myenv/bin/activate
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Set up venv, install dependencies, run tests'
